services:
    micayael.command.search_in_files:
        class: Micayael\CommandsBundle\Command\SearchInCodeCommand
        public: true
        arguments: ["%micayael_commands_configs%"]
        tags:
            - { name: console.command }

    micayael.command.verify:
        class: Micayael\CommandsBundle\Command\VerifyCodeCommand
        public: true
        arguments: ["%micayael_commands_configs%"]
        tags:
            - { name: console.command }

    micayael.command.phpcs:
        class: Micayael\CommandsBundle\Command\CSFixerCommand
        public: true
        arguments: ["%micayael_commands_configs%"]
        tags:
            - { name: console.command }

    micayael.command.test:
        class: Micayael\CommandsBundle\Command\TestsCommand
        public: true
        arguments: ["%micayael_commands_configs%"]
        tags:
            - { name: console.command }

    micayael.command.precommit:
        class: Micayael\CommandsBundle\Command\PrecommitCommand
        public: true
        tags:
            - { name: console.command }
